name: read-GRACE-harmonics
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - notebook
  - numpy
  - pyyaml
  - lxml
  - future
  - matplotlib
  - cartopy
  - netCDF4
  - h5py
  - pip
  - pip:
     - git+https://github.com/tsutterley/read-GRACE-geocenter.git
